# Generated by Django 2.2 on 2019-07-06 00:55

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserId', models.AutoField(db_column='USER_ID', primary_key=True, serialize=False)),
                ('UserName', models.TextField(db_column='USER_NAME', unique=True)),
                ('UserPw', models.TextField(db_column='USER_PASSWORD')),
                ('UserEmail', models.TextField(db_column='USER_EMAIL')),
                ('UserPhone', models.CharField(db_column='USER_PHONE', max_length=11, unique=True)),
                ('DateTime', models.DateTimeField(db_column='USER_TIME', default=django.utils.timezone.now)),
                ('Is_Superuser', models.BooleanField(db_column='ROOT', default=False)),
                ('Is_Active', models.BooleanField(db_column='ACTIVE', default=True)),
                ('Is_Banned', models.BooleanField(db_column='BANNED', default=False)),
            ],
            options={
                'db_table': 'user_info_base',
            },
        ),
        migrations.CreateModel(
            name='UserCollection',
            fields=[
                ('UserId', models.IntegerField(db_column='USER_ID', primary_key=True, serialize=False)),
                ('Star', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), db_column='STAR', size=None)),
                ('CreateDoc', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), db_column='CREATE', size=None)),
                ('UploadSource', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), db_column='UPLOAD', size=None)),
            ],
            options={
                'db_table': 'user_collection',
            },
        ),
        migrations.CreateModel(
            name='UserConcern',
            fields=[
                ('UserId', models.IntegerField(db_column='USER_ID', primary_key=True, serialize=False)),
                ('SourceId', models.UUIDField(db_column='SOURCE_ID')),
                ('Labels', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), db_column='LABELS', size=None)),
                ('Imp', models.IntegerField(db_column='IMP', default=-1)),
                ('HardLevel', models.IntegerField(db_column='HARD_LEVEL', default=-1)),
                ('Useful', models.IntegerField(db_column='USEFUL', default=-1)),
            ],
            options={
                'db_table': 'user_labels',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('UserId', models.IntegerField(db_column='USER_ID', primary_key=True, serialize=False)),
                ('Is_Member', models.BooleanField(db_column='MEMBER', default=False)),
                ('Is_Organizer', models.BooleanField(db_column='ORGANIZER', default=False)),
            ],
            options={
                'db_table': 'user_info_role',
            },
        ),
    ]
