# Generated by Django 2.2 on 2019-07-10 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='DateTime',
            field=models.DateTimeField(auto_now_add=True, db_column='USER_TIME'),
        ),
    ]
