# Generated by Django 2.2 on 2019-10-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userconcern',
            name='Is_Tag',
        ),
        migrations.AddField(
            model_name='userconcern',
            name='Is_Good',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userconcern',
            name='Is_Shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userconcern',
            name='SpendTime',
            field=models.IntegerField(db_column='SpendTime', default=0),
        ),
    ]
