# Generated by Django 2.2 on 2019-08-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190816_0359'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthorityCount',
        ),
        migrations.RemoveField(
            model_name='privilege',
            name='Is_Active',
        ),
        migrations.RemoveField(
            model_name='privilege',
            name='Is_Banned',
        ),
        migrations.AddField(
            model_name='user',
            name='Is_Active',
            field=models.BooleanField(db_column='Active', default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Is_Banned',
            field=models.BooleanField(db_column='Banned', default=False),
        ),
    ]
