# Generated by Django 2.2 on 2019-07-13 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190710_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Is_Developer',
            field=models.BooleanField(db_column='DEV', default=False),
        ),
    ]
