# Generated by Django 2.2 on 2019-10-24 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userdraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdraft',
            name='DontClear',
            field=models.BooleanField(default=False),
        ),
    ]
