# Generated by Django 3.0.3 on 2020-03-19 12:01

import django.contrib.postgres.fields
from django.db import migrations, models
import tools.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200301_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPLabelExtraProps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', tools.models.IdField(db_index=True)),
                ('PLabel', models.TextField(db_index=True, unique=True)),
                ('PropNames', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
            ],
            options={
                'db_table': 'user_record_plabel_props',
            },
        ),
        migrations.CreateModel(
            name='UserPropResolve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', tools.models.IdField(db_index=True)),
                ('PropName', models.TextField(db_index=True, unique=True)),
                ('FieldType', models.TextField(choices=[('TEXT', 'TextField'), ('ARRAY', 'ArrayField'), ('NUM', 'NumberField'), ('STR', 'StringField'), ('JSON', 'JsonField'), ('FILE', 'FileField'), ('BOOL', 'BooleanField')])),
                ('ResolveType', models.TextField(choices=[('NO', 'normal'), ('NM', 'name'), ('LO', 'location'), ('TI', 'time'), ('EV', 'event')], default='NO')),
                ('UpdateTime', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'user_record_prop_resolve',
            },
        ),
    ]
