# Generated by Django 3.0.3 on 2020-03-19 17:16

from django.db import migrations, models
import tools.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userplabelextraprops_userpropresolve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpropresolve',
            name='PropName',
            field=models.TextField(db_index=True, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userpropresolve',
            name='UserId',
            field=tools.models.IdField(db_index=True, editable=False),
        ),
    ]
