# Generated by Django 2.2 on 2019-09-02 10:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_courseauthority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrepository',
            name='UploadFile',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), default=list, size=None),
        ),
    ]
