# Generated by Django 3.0.3 on 2020-03-19 22:54

from django.db import migrations, models
import tools.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200319_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpropresolve',
            old_name='PropName',
            new_name='Key',
        ),
        migrations.RemoveField(
            model_name='userplabelextraprops',
            name='PLabel',
        ),
        migrations.AddField(
            model_name='userplabelextraprops',
            name='Key',
            field=models.TextField(db_index=True, default='', editable=False, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userplabelextraprops',
            name='UpdateTime',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userplabelextraprops',
            name='UserId',
            field=tools.models.IdField(db_index=True, editable=False),
        ),
    ]
