# Generated by Django 2.2 on 2019-10-27 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userdraft'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDraft',
        ),
    ]
