# Generated by Django 2.2 on 2019-10-27 15:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_delete_userdraft'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.BigIntegerField(db_column='UserId', db_index=True)),
                ('SourceId', models.BigIntegerField(db_column='SourceId', db_index=True)),
                ('SourceType', models.TextField(db_column='SourceType', db_index=True)),
                ('VersionId', models.IntegerField()),
                ('Name', models.TextField()),
                ('UpdateTime', models.DateField(auto_now=True, db_column='UpdateTime')),
                ('Content', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('DontClear', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user_draft',
            },
        ),
        migrations.AddConstraint(
            model_name='userdraft',
            constraint=models.UniqueConstraint(fields=('SourceId', 'VersionId'), name='DraftVersionControl'),
        ),
    ]
