# Generated by Django 2.2 on 2019-10-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20191027_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdraft',
            name='UpdateTime',
            field=models.DateTimeField(auto_now=True, db_column='UpdateTime'),
        ),
    ]
