# Generated by Django 2.2 on 2019-10-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20191028_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdraft',
            name='Deleted',
            field=models.BooleanField(default=True),
        ),
    ]
