# Generated by Django 2.2 on 2019-10-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_userdraft_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdraft',
            name='Deleted',
            field=models.BooleanField(default=False),
        ),
    ]
