# Generated by Django 3.0.3 on 2020-02-24 23:33

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import tools.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('CommentId', models.BigIntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('SourceId', models.BigIntegerField(db_column='Source', db_index=True)),
                ('TargetId', models.BigIntegerField(db_column='TARGET', db_index=True)),
                ('TargetUser', models.BigIntegerField(db_column='TARGET_USER', db_index=True)),
                ('Content', models.TextField(db_column='CONTENT', default='')),
                ('Owner', models.BigIntegerField(db_column='USER', db_index=True, default='0')),
                ('CreateTime', models.DateTimeField(auto_now_add=True, db_column='TIME')),
                ('IsUsed', models.BooleanField(db_column='DELETED', default=False)),
            ],
            options={
                'db_table': 'document_comment',
            },
        ),
        migrations.CreateModel(
            name='DocGraph',
            fields=[
                ('DocId', tools.models.IdField(primary_key=True, serialize=False)),
                ('Nodes', django.contrib.postgres.fields.ArrayField(base_field=tools.models.SettingField(validators=[tools.models.setting_check]), default=list, size=None)),
                ('Links', django.contrib.postgres.fields.ArrayField(base_field=tools.models.SettingField(validators=[tools.models.setting_check]), default=list, size=None)),
                ('Medias', django.contrib.postgres.fields.ArrayField(base_field=tools.models.SettingField(validators=[tools.models.setting_check]), default=list, size=None)),
                ('Svgs', django.contrib.postgres.fields.ArrayField(base_field=tools.models.SettingField(validators=[tools.models.setting_check]), default=list, size=None)),
                ('Conf', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
            options={
                'db_table': 'document_graph',
            },
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['SourceId', 'IsUsed'], name='Count_DocComment'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['TargetUser', 'IsUsed'], name='Count_ReplyComment'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['Owner', 'IsUsed'], name='Count_OwnerComment'),
        ),
    ]
