# Generated by Django 2.2 on 2019-10-27 15:30

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import document.models
import tools.models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphVersionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreateUser', models.BigIntegerField(db_column='User', db_index=True, editable=False)),
                ('CreateTime', models.DateTimeField(auto_now_add=True)),
                ('SourceId', models.BigIntegerField(db_column='SourceId', db_index=True, editable=False)),
                ('VersionId', models.SmallIntegerField(db_column='VersionId', default=0)),
                ('SourceType', models.TextField(default='DocGraph', editable=False)),
                ('Name', models.TextField(db_column='Name', default='Draft')),
                ('Is_Draft', models.BooleanField(db_column='Draft', default=True)),
                ('DontClear', models.BooleanField(default=False)),
                ('Nodes', django.contrib.postgres.fields.ArrayField(base_field=tools.models.SettingField(validators=[tools.models.setting_check]), default=document.models.node_setting, size=None)),
                ('Links', django.contrib.postgres.fields.ArrayField(base_field=tools.models.SettingField(validators=[tools.models.setting_check]), default=document.models.link_setting, size=None)),
                ('Paths', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(default=dict), size=None)),
                ('Conf', django.contrib.postgres.fields.jsonb.JSONField(default=document.models.graph_setting)),
            ],
            options={
                'db_table': 'document_graph_record',
            },
        ),
        migrations.RenameField(
            model_name='docgraph',
            old_name='Paths',
            new_name='Path',
        ),
        migrations.AddIndex(
            model_name='graphversionrecord',
            index=models.Index(fields=['SourceId', 'Is_Draft'], name='document_gr_SourceI_cb86f5_idx'),
        ),
        migrations.AddConstraint(
            model_name='graphversionrecord',
            constraint=models.UniqueConstraint(fields=('SourceId', 'VersionId'), name='GraphVersionControl'),
        ),
    ]
