# Generated by Django 3.0.3 on 2020-02-27 18:32

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import tools.models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docgraph',
            name='Complete',
            field=tools.models.LevelField(default=-1, validators=[django.core.validators.MinValueValidator(limit_value=-1), django.core.validators.MaxValueValidator(limit_value=100)]),
        ),
        migrations.AddField(
            model_name='docgraph',
            name='MainNodes',
            field=django.contrib.postgres.fields.ArrayField(base_field=tools.models.IdField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='docgraph',
            name='Size',
            field=models.IntegerField(default=0),
        ),
    ]
