# Generated by Django 2.2 on 2019-07-10 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Time',
            field=models.DateTimeField(auto_now_add=True, db_column='TIME'),
        ),
        migrations.AlterField(
            model_name='docinfo',
            name='CountCacheTime',
            field=models.DateTimeField(auto_now=True, db_column='CACHE_TIME'),
        ),
    ]
