# Generated by Django 2.2 on 2019-10-05 19:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import document.models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docgraph',
            name='Conf',
            field=django.contrib.postgres.fields.jsonb.JSONField(db_column='Conf', default=document.models.graph_setting),
        ),
    ]
