# Generated by Django 2.2 on 2019-07-13 16:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_auto_20190710_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docgraph',
            name='Keywords',
        ),
        migrations.AddField(
            model_name='docinfo',
            name='Keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), db_column='KEYWORDS', default=list, size=None),
        ),
    ]
