# Generated by Django 3.0.3 on 2020-03-02 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_auto_20200301_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='docgraph',
            name='LinkFailed',
            field=models.BooleanField(default=False),
        ),
    ]
