# Generated by Django 2.2 on 2019-07-13 18:16

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_auto_20190714_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='docgraph',
            name='Conf',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), db_column='CONF', default=list, size=None),
        ),
        migrations.AlterField(
            model_name='docinfo',
            name='Area',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), db_column='AREA', default=list, size=None),
        ),
    ]
