# Generated by Django 2.2 on 2019-10-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_auto_20191028_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphversionrecord',
            name='CreateTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
