# Generated by Django 2.2 on 2019-07-06 05:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('GroupId', models.UUIDField(db_column='GROUP_ID', primary_key=True, serialize=False)),
                ('GroupName', models.TextField(db_column='GROUP_NAME', unique=True)),
                ('CreateUser', models.IntegerField(db_column='GROUP_CREATOR')),
                ('Owner', models.IntegerField(db_column='OWNER')),
                ('Manager', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), db_column='MANAGER', size=None)),
                ('Member', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), db_column='Member', size=None)),
            ],
            options={
                'db_table': 'group_info_base',
            },
        ),
    ]
