# Generated by Django 2.2 on 2019-07-06 00:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelRecord',
            fields=[
                ('uuid', models.UUIDField(db_column='UUID', primary_key=True, serialize=False)),
                ('ExcelURL', models.URLField(db_column='URL')),
                ('UserId', models.IntegerField(db_column='USER_ID')),
                ('Nodes', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), db_column='NODES', size=None)),
            ],
            options={
                'db_table': 'excel_upload',
            },
        ),
    ]
