# Generated by Django 2.2 on 2019-10-23 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subgraph', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediactrl',
            old_name='IsUsed',
            new_name='Is_Used',
        ),
        migrations.RenameField(
            model_name='nodectrl',
            old_name='IsUsed',
            new_name='Is_Used',
        ),
        migrations.RenameField(
            model_name='relationshipctrl',
            old_name='IsUsed',
            new_name='Is_Used',
        ),
    ]
