# Generated by Django 2.2 on 2019-09-10 15:48

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subgraph', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('NodeId', models.BigIntegerField(primary_key=True, serialize=False)),
                ('Language', models.TextField(default='auto')),
                ('Keywords', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('Text', django.contrib.postgres.fields.jsonb.JSONField(default={'auto': '', 'en': '', 'text': {}, 'zh': ''})),
                ('Star', models.IntegerField(db_column='Star', default=0)),
                ('Hot', models.IntegerField(db_column='Hot', default=1)),
            ],
            options={
                'db_table': 'graph_node_text',
            },
        ),
        migrations.AlterModelTable(
            name='fragment',
            table='graph_node_fragment',
        ),
    ]
