# Generated by Django 2.2 on 2019-08-15 19:59

from django.db import migrations
import tools.models


class Migration(migrations.Migration):

    dependencies = [
        ('subgraph', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medianode',
            name='Topic',
            field=tools.models.TopicField(db_index=True, default=dict, validators=[tools.models.validate_topic]),
        ),
        migrations.AlterField(
            model_name='nodeinfo',
            name='Topic',
            field=tools.models.TopicField(db_index=True, default=dict, validators=[tools.models.validate_topic]),
        ),
    ]
