# Generated by Django 2.2 on 2019-07-06 08:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subgraph', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archproject',
            name='Architect',
        ),
        migrations.RemoveField(
            model_name='project',
            name='Latitude',
        ),
        migrations.RemoveField(
            model_name='project',
            name='Location',
        ),
        migrations.RemoveField(
            model_name='project',
            name='Longitude',
        ),
        migrations.AddField(
            model_name='archproject',
            name='Latitude',
            field=models.FloatField(db_column='LATITUDE', default=0),
        ),
        migrations.AddField(
            model_name='archproject',
            name='Location',
            field=models.TextField(db_column='LOCATION', default='Beijing'),
        ),
        migrations.AddField(
            model_name='archproject',
            name='Longitude',
            field=models.FloatField(db_column='LONGITUDE', default=0),
        ),
        migrations.AddField(
            model_name='archproject',
            name='WorkTeam',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), db_column='WORK_TEAM', default=list, size=None),
        ),
        migrations.AddField(
            model_name='project',
            name='Leader',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), db_column='LEADER', default=list, size=None),
        ),
        migrations.AlterField(
            model_name='person',
            name='PeriodEnd',
            field=models.TextField(db_column='PERIOD_END'),
        ),
        migrations.AlterField(
            model_name='person',
            name='PeriodStart',
            field=models.TextField(db_column='PERIOD_START'),
        ),
        migrations.AlterField(
            model_name='project',
            name='PeriodEnd',
            field=models.TextField(db_column='PERIOD_END'),
        ),
        migrations.AlterField(
            model_name='project',
            name='PeriodStart',
            field=models.TextField(db_column='PERIOD_START'),
        ),
    ]
