# Generated by Django 3.0.3 on 2020-02-25 01:43

from django.db import migrations
import tools.models


class Migration(migrations.Migration):

    dependencies = [
        ('subgraph', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fragmentinfo',
            name='Translate',
            field=tools.models.TranslateField(default=tools.models.default_text),
        ),
        migrations.AddField(
            model_name='mediainfo',
            name='Translate',
            field=tools.models.TranslateField(default=tools.models.default_text),
        ),
        migrations.AddField(
            model_name='relationshipinfo',
            name='Translate',
            field=tools.models.TranslateField(default=tools.models.default_text),
        ),
    ]
