# Generated by Django 2.2 on 2019-10-20 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subgraph', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='relationshipctrl',
            table='graph_link_ctrl',
        ),
    ]
