# Generated by Django 2.2 on 2019-08-12 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subgraph', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodectrl',
            name='Type',
            field=models.TextField(db_column='Type', db_index=True, default='StrNode'),
        ),
    ]
