# Generated by Django 2.2 on 2019-07-19 17:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subgraph', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='Contributor',
            field=django.contrib.postgres.fields.jsonb.JSONField(db_column='CONTRIBUTOR'),
        ),
        migrations.AlterField(
            model_name='node',
            name='FeatureVec',
            field=django.contrib.postgres.fields.jsonb.JSONField(db_column='FEATURE_VECTOR', default=dict),
        ),
        migrations.AlterField(
            model_name='node',
            name='History',
            field=models.BigIntegerField(db_column='HISTORY'),
        ),
        migrations.AlterField(
            model_name='node',
            name='PrimaryLabel',
            field=models.TextField(db_column='P_LABEL', db_index=True),
        ),
    ]
