# Generated by Django 3.0.3 on 2020-02-27 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subgraph', '0002_auto_20200225_0143'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentCtrl',
        ),
    ]
