# Generated by Django 2.2 on 2019-08-12 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subgraph', '0002_nodectrl_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archproject',
            name='Latitude',
        ),
        migrations.RemoveField(
            model_name='archproject',
            name='Longitude',
        ),
    ]
