# Generated by Django 2.2 on 2019-10-24 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subgraph', '0002_auto_20191023_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediactrl',
            name='Thumb',
            field=models.TextField(default=''),
        ),
    ]
