# Generated by Django 2.2 on 2019-09-11 02:29

import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subgraph', '0002_auto_20190910_2348'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Translate',
        ),
        migrations.RemoveField(
            model_name='text',
            name='Hot',
        ),
        migrations.RemoveField(
            model_name='text',
            name='Star',
        ),
        migrations.AddField(
            model_name='nodeinfo',
            name='Translate',
            field=django.contrib.postgres.fields.hstore.HStoreField(default={'en': '', 'zh': ''}),
        ),
        migrations.AddField(
            model_name='text',
            name='Is_Bound',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='text',
            name='Translate',
            field=django.contrib.postgres.fields.hstore.HStoreField(default={'en': '', 'zh': ''}),
        ),
        migrations.AlterField(
            model_name='text',
            name='Text',
            field=models.TextField(default=''),
        ),
    ]
