# Generated by Django 2.2 on 2019-10-20 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subgraph', '0002_auto_20191021_0444'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseAuthority',
            fields=[
                ('SourceId', models.BigIntegerField(db_index=True, primary_key=True, serialize=False)),
                ('SourceType', models.TextField(db_index=True)),
                ('Used', models.BooleanField(db_column='used', default=True)),
                ('Common', models.BooleanField(db_column='common', default=True)),
                ('Shared', models.BooleanField(db_column='shared', default=False)),
                ('OpenSource', models.BooleanField(db_column='open', default=False)),
                ('Payment', models.BooleanField(db_column='payment', default=False)),
                ('Vip', models.BooleanField(db_column='vip', default=False)),
                ('HighVip', models.BooleanField(db_column='high_vip', default=False)),
            ],
            options={
                'db_table': 'graph_authority',
            },
        ),
        migrations.AddIndex(
            model_name='baseauthority',
            index=models.Index(fields=['Used', 'Common'], name='graph_autho_used_64bed9_idx'),
        ),
    ]
