# Generated by Django 2.2 on 2019-09-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subgraph', '0002_nodenormal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archproject',
            name='Language',
            field=models.TextField(db_column='Language', default='auto'),
        ),
        migrations.AlterField(
            model_name='archproject',
            name='MainPic',
            field=models.BigIntegerField(db_column='Main', null=True),
        ),
        migrations.AlterField(
            model_name='basedoc',
            name='Language',
            field=models.TextField(db_column='Language', default='auto'),
        ),
        migrations.AlterField(
            model_name='basedoc',
            name='MainPic',
            field=models.BigIntegerField(db_column='Main', null=True),
        ),
        migrations.AlterField(
            model_name='nodenormal',
            name='Language',
            field=models.TextField(db_column='Language', default='auto'),
        ),
        migrations.AlterField(
            model_name='nodenormal',
            name='MainPic',
            field=models.BigIntegerField(db_column='Main', null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='Language',
            field=models.TextField(db_column='Language', default='auto'),
        ),
        migrations.AlterField(
            model_name='person',
            name='MainPic',
            field=models.BigIntegerField(db_column='Main', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='Language',
            field=models.TextField(db_column='Language', default='auto'),
        ),
        migrations.AlterField(
            model_name='project',
            name='MainPic',
            field=models.BigIntegerField(db_column='Main', null=True),
        ),
    ]
