# Generated by Django 2.2 on 2019-09-15 20:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subgraph', '0003_auto_20190913_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='SourceType',
            field=models.TextField(default='Node'),
        ),
        migrations.AlterField(
            model_name='nodectrl',
            name='CountCacheTime',
            field=models.DateTimeField(db_column='CacheTime', default=django.utils.timezone.now),
        ),
    ]
