# Generated by Django 2.2 on 2019-08-12 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subgraph', '0003_auto_20190812_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodectrl',
            name='ImportMethod',
            field=models.TextField(db_column='ImportMethod', db_index=True, default='Excel'),
        ),
    ]
