# Generated by Django 2.2 on 2019-08-31 22:54

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subgraph', '0003_auto_20190816_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fragment',
            fields=[
                ('NodeId', models.BigIntegerField(primary_key=True, serialize=False)),
                ('Keywords', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), db_column='Keyword', default=list, size=None)),
                ('Content', models.TextField(db_column='Content', default='')),
                ('Props', django.contrib.postgres.fields.jsonb.JSONField(db_column='Props', default=dict)),
                ('Labels', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), db_column='Labels', default=list, size=None)),
                ('CreateTime', models.DateField(db_column='CreateTime', default=django.utils.timezone.now)),
                ('CreateUser', models.BigIntegerField(db_column='User')),
            ],
            options={
                'db_table': 'graph_normal_node',
            },
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
