# Generated by Django 2.2 on 2019-07-10 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subgraph', '0003_node_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='ImportTime',
            field=models.DateTimeField(auto_now_add=True, db_column='IMPORT_TIME'),
        ),
    ]
