# Generated by Django 3.0.3 on 2020-03-03 11:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subgraph', '0003_delete_documentctrl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledge',
            name='Labels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='mediactrl',
            name='Labels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='nodectrl',
            name='Labels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None),
        ),
    ]
