# Generated by Django 2.2 on 2019-09-11 02:33

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import subgraph.models


class Migration(migrations.Migration):

    dependencies = [
        ('subgraph', '0003_auto_20190911_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='Hot',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='text',
            name='Star',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nodeinfo',
            name='Translate',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=subgraph.models.translation),
        ),
        migrations.AlterField(
            model_name='text',
            name='Translate',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=subgraph.models.translation),
        ),
    ]
