# Generated by Django 3.0.3 on 2020-03-16 18:38

from django.db import migrations, models
import tools.models


class Migration(migrations.Migration):

    dependencies = [
        ('subgraph', '0004_auto_20200303_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fragmentinfo',
            name='ItemType',
            field=tools.models.TypeField(db_index=True, default='node', editable=False),
        ),
        migrations.AlterField(
            model_name='fragmentinfo',
            name='Src',
            field=models.TextField(default=''),
        ),
    ]
