# Generated by Django 2.2 on 2019-10-21 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subgraph', '0004_auto_20191021_0712'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BaseDoc',
            new_name='BaseDocGraph',
        ),
    ]
