# Generated by Django 2.2 on 2019-07-13 16:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subgraph', '0004_auto_20190710_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='Alias',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), db_column='ALIAS', default=list, size=None),
        ),
        migrations.AddField(
            model_name='node',
            name='Description',
            field=models.TextField(db_column='DESCRIPTION', default=''),
        ),
        migrations.AlterField(
            model_name='node',
            name='CreateUser',
            field=models.IntegerField(db_column='USER', default='0', editable=False),
        ),
        migrations.AlterField(
            model_name='node',
            name='ImportMethod',
            field=models.CharField(db_column='IMPORT_METHOD', editable=False, max_length=30),
        ),
    ]
