# Generated by Django 2.2 on 2019-09-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subgraph', '0004_auto_20190916_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archproject',
            name='MainPic',
            field=models.BigIntegerField(db_column='Main', default=-1),
        ),
        migrations.AlterField(
            model_name='basedoc',
            name='MainPic',
            field=models.BigIntegerField(db_column='Main', default=-1),
        ),
        migrations.AlterField(
            model_name='nodenormal',
            name='MainPic',
            field=models.BigIntegerField(db_column='Main', default=-1),
        ),
        migrations.AlterField(
            model_name='person',
            name='MainPic',
            field=models.BigIntegerField(db_column='Main', default=-1),
        ),
        migrations.AlterField(
            model_name='project',
            name='MainPic',
            field=models.BigIntegerField(db_column='Main', default=-1),
        ),
    ]
