# Generated by Django 2.2 on 2019-11-01 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subgraph', '0004_mediactrl_primarylabel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediactrl',
            name='MediaId',
            field=models.BigIntegerField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='relationshipctrl',
            name='LinkId',
            field=models.BigIntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
