# Generated by Django 2.2 on 2019-08-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subgraph', '0004_nodectrl_importmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='Gender',
            field=models.TextField(db_column='Gender', default='Man'),
        ),
        migrations.AddField(
            model_name='person',
            name='Job',
            field=models.TextField(db_column='Job', default=''),
        ),
    ]
