# Generated by Django 2.2 on 2019-07-13 18:44

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subgraph', '0005_auto_20190714_0034'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationDoc',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('Name', models.TextField(db_column='NAME', default='Beijing')),
                ('Alias', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), db_column='ALIAS', default=list, size=None)),
                ('Doc', django.contrib.postgres.fields.jsonb.JSONField(db_column='DOC', default={})),
                ('Format_Name', models.IntegerField(db_column='FORMAT_ID', default=0)),
            ],
            options={
                'db_table': 'loc_doc',
            },
        ),
        migrations.RemoveField(
            model_name='archproject',
            name='Latitude',
        ),
        migrations.RemoveField(
            model_name='archproject',
            name='Longitude',
        ),
    ]
