# Generated by Django 2.2 on 2019-10-05 19:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subgraph', '0005_auto_20190917_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledge',
            name='CreateUser',
        ),
        migrations.RemoveField(
            model_name='knowledge',
            name='LinkedSource',
        ),
        migrations.AddField(
            model_name='aftervisit',
            name='CreatorId',
            field=models.BigIntegerField(db_column='CreatorId', db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='aftervisit',
            name='Is_UserMade',
            field=models.BooleanField(db_column='Is_UserMade', db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='doc2node',
            name='CreatorId',
            field=models.BigIntegerField(db_column='CreatorId', db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='doc2node',
            name='DocImp',
            field=models.IntegerField(db_column='DocImp', default=1),
        ),
        migrations.AddField(
            model_name='doc2node',
            name='Is_UserMade',
            field=models.BooleanField(db_column='Is_UserMade', db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='knowledge',
            name='CreatorId',
            field=models.BigIntegerField(db_column='CreatorId', db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='knowledge',
            name='Labels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='mentiontogether',
            name='CreatorId',
            field=models.BigIntegerField(db_column='CreatorId', db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='mentiontogether',
            name='Is_UserMade',
            field=models.BooleanField(db_column='Is_UserMade', db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='searchtogether',
            name='CreatorId',
            field=models.BigIntegerField(db_column='CreatorId', db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='searchtogether',
            name='Is_UserMade',
            field=models.BooleanField(db_column='Is_UserMade', db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='topic2node',
            name='CreatorId',
            field=models.BigIntegerField(db_column='CreatorId', db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='topic2node',
            name='Is_UserMade',
            field=models.BooleanField(db_column='Is_UserMade', db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='topic2topic',
            name='CreatorId',
            field=models.BigIntegerField(db_column='CreatorId', db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='topic2topic',
            name='Is_UserMade',
            field=models.BooleanField(db_column='Is_UserMade', db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='Is_UserMade',
            field=models.BooleanField(db_column='Is_UserMade', db_index=True, default=True),
        ),
    ]
