# Generated by Django 2.2 on 2019-11-01 01:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subgraph', '0005_auto_20191101_0112'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaseAuthority',
        ),
        migrations.RenameField(
            model_name='mediactrl',
            old_name='MediaId',
            new_name='ItemId',
        ),
        migrations.RenameField(
            model_name='nodectrl',
            old_name='NodeId',
            new_name='ItemId',
        ),
        migrations.RenameField(
            model_name='relationshipctrl',
            old_name='LinkId',
            new_name='ItemId',
        ),
        migrations.RemoveField(
            model_name='mediactrl',
            name='History',
        ),
        migrations.RemoveField(
            model_name='mediactrl',
            name='UploadTime',
        ),
        migrations.AddField(
            model_name='mediactrl',
            name='CreateTime',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mediactrl',
            name='Is_Common',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mediactrl',
            name='Is_OpenSource',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mediactrl',
            name='Is_Shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mediactrl',
            name='ItemType',
            field=models.TextField(default='media'),
        ),
        migrations.AddField(
            model_name='nodectrl',
            name='Is_Common',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='nodectrl',
            name='Is_OpenSource',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nodectrl',
            name='Is_Shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nodectrl',
            name='ItemType',
            field=models.TextField(default='node'),
        ),
        migrations.AddField(
            model_name='relationshipctrl',
            name='Is_Common',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='relationshipctrl',
            name='Is_OpenSource',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relationshipctrl',
            name='Is_Shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relationshipctrl',
            name='ItemType',
            field=models.TextField(default='link'),
        ),
        migrations.AlterField(
            model_name='mediactrl',
            name='CreateUser',
            field=models.BigIntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='mediactrl',
            name='FileName',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mediactrl',
            name='Is_Used',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='mediactrl',
            name='Is_UserMade',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='mediactrl',
            name='PrimaryLabel',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='nodectrl',
            name='CreateTime',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='nodectrl',
            name='CreateUser',
            field=models.BigIntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='nodectrl',
            name='Is_Used',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='nodectrl',
            name='Is_UserMade',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='nodectrl',
            name='PrimaryLabel',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='relationshipctrl',
            name='CreateTime',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='relationshipctrl',
            name='CreateUser',
            field=models.BigIntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='relationshipctrl',
            name='End',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='relationshipctrl',
            name='EndPLabel',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='relationshipctrl',
            name='EndType',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='relationshipctrl',
            name='Is_Used',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='relationshipctrl',
            name='Is_UserMade',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='relationshipctrl',
            name='Start',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='relationshipctrl',
            name='StartPLabel',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='relationshipctrl',
            name='StartType',
            field=models.TextField(),
        ),
    ]
