# Generated by Django 2.2 on 2019-07-13 18:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subgraph', '0006_auto_20190714_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationdoc',
            name='Doc',
            field=django.contrib.postgres.fields.jsonb.JSONField(db_column='DOC', default=dict),
        ),
    ]
