# Generated by Django 2.2 on 2019-11-01 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subgraph', '0006_auto_20191101_0120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archproject',
            old_name='NodeId',
            new_name='ItemId',
        ),
        migrations.RenameField(
            model_name='audio',
            old_name='MediaId',
            new_name='ItemId',
        ),
        migrations.RenameField(
            model_name='basedocgraph',
            old_name='NodeId',
            new_name='ItemId',
        ),
        migrations.RenameField(
            model_name='doc2node',
            old_name='LinkId',
            new_name='ItemId',
        ),
        migrations.RenameField(
            model_name='fragment',
            old_name='NodeId',
            new_name='ItemId',
        ),
        migrations.RenameField(
            model_name='frequencycount',
            old_name='LinkId',
            new_name='ItemId',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='MediaId',
            new_name='ItemId',
        ),
        migrations.RenameField(
            model_name='knowledge',
            old_name='LinkId',
            new_name='ItemId',
        ),
        migrations.RenameField(
            model_name='nodenormal',
            old_name='NodeId',
            new_name='ItemId',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='NodeId',
            new_name='ItemId',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='NodeId',
            new_name='ItemId',
        ),
        migrations.RenameField(
            model_name='text',
            old_name='MediaId',
            new_name='ItemId',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='MediaId',
            new_name='ItemId',
        ),
    ]
