# Generated by Django 2.2 on 2019-07-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subgraph', '0007_auto_20190714_0245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationdoc',
            name='Format_Name',
        ),
        migrations.AddField(
            model_name='locationdoc',
            name='LocId',
            field=models.TextField(db_column='LOC_ID', default='ChIJ58KMhbNLzJQRwfhoMaMlugA'),
        ),
    ]
