# Generated by Django 2.2 on 2019-07-19 13:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseAuthority',
            fields=[
                ('id', models.BigIntegerField(db_column='id', primary_key=True, serialize=False)),
                ('Owner', models.IntegerField(db_column='createUser')),
                ('ChangeState', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), db_column='changeStatePrivilege', default=list, size=None)),
                ('SharedTo', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), db_column='SharePrivilege', default=list, size=None)),
                ('Query', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), db_column='readPrivilege', default=list, size=None)),
                ('Write', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), db_column='writePrivilege', default=list, size=None)),
                ('Reference', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), db_column='referencePrivilege', default=list, size=None)),
                ('Delete', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), db_column='deletePrivilege', default=list, size=None)),
                ('Export', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), db_column='exportPrivilege', default=list, size=None)),
                ('Payment', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), db_column='payment', default=list, size=None)),
                ('Source_type', models.TextField(db_column='type', default='Document')),
                ('Common', models.BooleanField(db_column='common', default=True)),
                ('Shared', models.BooleanField(db_column='shared', default=False)),
                ('Paid', models.BooleanField(db_column='paid', default=False)),
            ],
            options={
                'db_table': 'authority_base',
            },
        ),
    ]
