# Generated by Django 2.2 on 2019-10-20 20:26

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVersionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreateUser', models.BigIntegerField(db_column='User', editable=False)),
                ('CreateTime', models.DateTimeField(auto_now_add=True)),
                ('SourceId', models.BigIntegerField(db_column='SourceId', db_index=True, editable=False)),
                ('SourceType', models.TextField(db_column='Type', default='Document', editable=False)),
                ('Name', models.TextField(db_column='Name')),
                ('VersionId', models.SmallIntegerField(db_column='VersionId')),
                ('Is_Draft', models.BooleanField(db_column='Draft', db_index=True)),
                ('BaseHistory', models.BigIntegerField(db_column='BaseHis', db_index=True)),
                ('GraphContent', django.contrib.postgres.fields.jsonb.JSONField(db_column='GraphContent')),
                ('PaperContent', django.contrib.postgres.fields.jsonb.JSONField(db_column='PaperContent')),
            ],
            options={
                'db_table': 'history_doc_version_record',
            },
        ),
        migrations.CreateModel(
            name='ErrorRecord',
            fields=[
                ('SourceId', models.BigIntegerField(db_column='SourceId', primary_key=True, serialize=False)),
                ('SourceLabel', models.TextField(db_column='Label', db_index=True, default=0)),
                ('BugType', models.TextField(db_column='Type')),
                ('CreateUser', models.BigIntegerField(db_column='User')),
                ('CreateTime', models.DateTimeField(auto_now_add=True, db_column='Time')),
                ('Is_Solved', models.BooleanField(db_column='Solved', db_index=True, default=False)),
                ('OriginData', django.contrib.postgres.fields.jsonb.JSONField(db_column='CONTENT', default=dict)),
            ],
            options={
                'db_table': 'history_error_record',
            },
        ),
        migrations.CreateModel(
            name='LocationsRecord',
            fields=[
                ('RecordId', models.AutoField(db_column='Locations', primary_key=True, serialize=False)),
                ('Location', models.TextField(db_column='NAME')),
                ('Is_Done', models.BooleanField(db_column='DONE', default=False)),
            ],
            options={
                'db_table': 'history_loc_record',
            },
        ),
        migrations.CreateModel(
            name='NodeVersionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreateUser', models.BigIntegerField(db_column='User', editable=False)),
                ('CreateTime', models.DateTimeField(auto_now_add=True)),
                ('SourceId', models.BigIntegerField(db_column='SourceId', db_index=True, editable=False)),
                ('SourceType', models.TextField(db_column='Type', editable=False)),
                ('Name', models.TextField(db_column='Name')),
                ('VersionId', models.SmallIntegerField(db_column='VersionId')),
                ('Is_Draft', models.BooleanField(db_column='Draft', db_index=True)),
                ('Content', django.contrib.postgres.fields.jsonb.JSONField(db_column='Content')),
            ],
            options={
                'db_table': 'history_version_record',
            },
        ),
        migrations.CreateModel(
            name='TransRecord',
            fields=[
                ('RecordId', models.AutoField(db_column='Trans', primary_key=True, serialize=False)),
                ('Lang', models.TextField(db_column='TYPE', db_index=True)),
                ('Name', models.TextField(db_column='NAME')),
                ('Is_Done', models.BooleanField(db_column='DONE')),
            ],
            options={
                'db_table': 'history_trans_record',
            },
        ),
        migrations.CreateModel(
            name='WarnRecord',
            fields=[
                ('SourceId', models.BigIntegerField(db_column='SourceId', primary_key=True, serialize=False)),
                ('SourceLabel', models.TextField(db_column='Label', db_index=True, default=0)),
                ('BugType', models.TextField(db_column='Type')),
                ('CreateUser', models.BigIntegerField(db_column='User')),
                ('CreateTime', models.DateTimeField(auto_now_add=True, db_column='Time')),
                ('Is_Solved', models.BooleanField(db_column='Solved', db_index=True, default=False)),
                ('WarnContent', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), db_column='Content', default=list, size=None)),
            ],
            options={
                'db_table': 'history_warn_record',
            },
        ),
        migrations.AddIndex(
            model_name='nodeversionrecord',
            index=models.Index(fields=['SourceId', 'Is_Draft'], name='history_ver_SourceI_98f9d7_idx'),
        ),
        migrations.AddConstraint(
            model_name='nodeversionrecord',
            constraint=models.UniqueConstraint(fields=('SourceId', 'VersionId'), name='NodeVersionControl'),
        ),
        migrations.AddIndex(
            model_name='documentversionrecord',
            index=models.Index(fields=['SourceId', 'Is_Draft'], name='history_doc_SourceI_57ad2a_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentversionrecord',
            constraint=models.UniqueConstraint(fields=('SourceId', 'VersionId'), name='DocVersionControl'),
        ),
    ]
