# Generated by Django 3.0.3 on 2020-02-24 23:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import record.models
import tools.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GraphVersionRecord',
            fields=[
                ('DocId', tools.models.IdField(primary_key=True, serialize=False)),
                ('CreateUser', models.BigIntegerField(db_column='User', db_index=True, editable=False)),
                ('CreateTime', models.DateTimeField(auto_now=True)),
                ('BranchId', models.IntegerField(db_column='VersionId', default=0)),
                ('BranchName', models.TextField(default='NewBranch')),
                ('BranchDescription', models.TextField(default='')),
                ('IsUsed', models.BooleanField(default=True)),
                ('IsMerged', models.BooleanField(default=False)),
                ('IsCurrent', models.BooleanField(default=False)),
                ('Content', django.contrib.postgres.fields.jsonb.JSONField(default=record.models.default_graph)),
            ],
            options={
                'db_table': 'record_document_graph_branch',
            },
        ),
        migrations.CreateModel(
            name='ItemDraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SourceId', models.BigIntegerField(db_index=True, editable=False)),
                ('SourceType', tools.models.TypeField(db_index=True, editable=False)),
                ('SourceLabel', models.TextField(db_index=True, default='')),
                ('UpdateTime', models.DateTimeField(auto_now=True)),
                ('CreateUser', tools.models.IdField(editable=False)),
                ('CreateType', models.TextField(default='USER')),
                ('Name', models.TextField(db_column='Name', default='Draft')),
                ('IsUsed', models.BooleanField(default=True)),
                ('DontClear', models.BooleanField(default=False)),
                ('Content', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('IsAuto', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'record_item_draft',
            },
        ),
        migrations.CreateModel(
            name='ItemVersionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SourceId', models.BigIntegerField(db_index=True, editable=False)),
                ('SourceType', tools.models.TypeField(db_index=True, editable=False)),
                ('SourceLabel', models.TextField(db_index=True, default='')),
                ('UpdateTime', models.DateTimeField(auto_now=True)),
                ('CreateUser', tools.models.IdField(editable=False)),
                ('CreateType', models.TextField(default='USER')),
                ('Name', models.TextField(db_column='Name', default='Draft')),
                ('IsUsed', models.BooleanField(default=True)),
                ('DontClear', models.BooleanField(default=False)),
                ('Content', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('VersionId', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'record_item_version',
            },
        ),
        migrations.CreateModel(
            name='LocationsRecord',
            fields=[
                ('RecordId', models.AutoField(db_column='Locations', primary_key=True, serialize=False)),
                ('Location', models.TextField(db_column='NAME')),
                ('Is_Done', models.BooleanField(db_column='DONE', default=False)),
            ],
            options={
                'db_table': 'record_location',
            },
        ),
        migrations.CreateModel(
            name='TransRecord',
            fields=[
                ('RecordId', models.AutoField(db_column='Trans', primary_key=True, serialize=False)),
                ('Lang', models.TextField(db_column='TYPE', db_index=True)),
                ('Name', models.TextField(db_column='NAME')),
                ('Is_Done', models.BooleanField(db_column='DONE')),
            ],
            options={
                'db_table': 'record_translation',
            },
        ),
        migrations.AddConstraint(
            model_name='itemversionrecord',
            constraint=models.UniqueConstraint(fields=('SourceId', 'VersionId'), name='ItemVersionControl'),
        ),
        migrations.AddConstraint(
            model_name='itemdraft',
            constraint=models.UniqueConstraint(fields=('SourceId', 'CreateUser'), name='ItemDraftControl'),
        ),
        migrations.AddConstraint(
            model_name='graphversionrecord',
            constraint=models.UniqueConstraint(fields=('DocId', 'BranchId'), name='GraphVersionControl'),
        ),
    ]
