# Generated by Django 3.0.3 on 2020-02-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemDraft',
        ),
        migrations.AddField(
            model_name='itemversionrecord',
            name='IsAuto',
            field=models.BooleanField(default=False),
        ),
    ]
