# Generated by Django 2.2 on 2019-10-27 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentVersionRecord',
        ),
    ]
