# Generated by Django 2.2 on 2019-08-12 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='errorrecord',
            name='RecordId',
        ),
        migrations.RemoveField(
            model_name='warnrecord',
            name='RecordId',
        ),
        migrations.AlterField(
            model_name='errorrecord',
            name='SourceId',
            field=models.BigIntegerField(db_column='SourceId', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='warnrecord',
            name='SourceId',
            field=models.BigIntegerField(db_column='SourceId', primary_key=True, serialize=False),
        ),
    ]
