# Generated by Django 2.2 on 2019-10-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_delete_documentversionrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorrecord',
            name='CreateTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='warnrecord',
            name='CreateTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
