# Generated by Django 3.0.3 on 2020-03-16 18:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import record.models
import tools.models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_itemversionrecord_isdraft'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVersionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DocId', tools.models.IdField()),
                ('CreateUser', models.BigIntegerField(db_column='User', db_index=True, editable=False)),
                ('CreateTime', models.DateTimeField(auto_now=True)),
                ('BranchId', tools.models.IdField()),
                ('BranchName', models.TextField(default='NewBranch')),
                ('BranchDescription', models.TextField(default='')),
                ('IsUsed', models.BooleanField(default=True)),
                ('IsMerged', models.BooleanField(default=False)),
                ('IsCurrent', models.BooleanField(default=False)),
                ('Content', django.contrib.postgres.fields.jsonb.JSONField(default=record.models.default_graph)),
            ],
            options={
                'db_table': 'record_document_document_branch',
            },
        ),
        migrations.DeleteModel(
            name='GraphVersionRecord',
        ),
        migrations.RenameField(
            model_name='locationsrecord',
            old_name='Is_Done',
            new_name='IsDone',
        ),
        migrations.RenameField(
            model_name='transrecord',
            old_name='Is_Done',
            new_name='IsDone',
        ),
        migrations.AddConstraint(
            model_name='documentversionrecord',
            constraint=models.UniqueConstraint(fields=('DocId', 'BranchId'), name='GraphVersionControl'),
        ),
    ]
