# Generated by Django 2.2 on 2019-07-19 13:47

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaNode',
            fields=[
                ('id', models.Field(db_column='ID', primary_key=True, serialize=False)),
                ('FileName', models.TextField(db_column='NAME')),
                ('Format', models.TextField(db_column='FORMAT')),
                ('Url', models.URLField(db_column='URL', default='')),
                ('UploadUser', models.IntegerField(db_column='UPLOAD_USER')),
                ('UploadTime', models.DateTimeField(auto_now_add=True, db_column='UPLOAD_TIME')),
                ('Description', models.TextField(db_column='DESCRIPTION', default='None')),
                ('AbbrPic', models.URLField(db_column='CONTENT', default='')),
            ],
            options={
                'db_table': 'media_base',
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('medianode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='media.MediaNode')),
                ('Tags', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), db_column='TAGS', default=list, size=None)),
                ('Rels', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), db_column='RELS', default=list, size=None)),
            ],
            options={
                'db_table': 'paper',
            },
            bases=('media.medianode',),
        ),
    ]
