# Generated by Django 2.2 on 2019-07-06 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medianode',
            name='Url',
            field=models.URLField(db_column='URL', default=''),
        ),
    ]
