# Generated by Django 2.2 on 2019-07-10 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_medianode_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medianode',
            name='UploadTime',
            field=models.DateTimeField(auto_now_add=True, db_column='UPLOAD_TIME'),
        ),
    ]
