# Generated by Django 2.2 on 2019-07-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceBlockId',
            fields=[
                ('BlockId', models.IntegerField(db_column='BLOCK_ID', db_index=True)),
                ('OutId', models.BigIntegerField(db_column='OUT_ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'global_doc_id',
            },
        ),
        migrations.CreateModel(
            name='GlobalDeviceBlock',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('DeviceId', models.SmallIntegerField(db_column='LabelId')),
                ('RegisterTime', models.DateTimeField(auto_now_add=True, db_column='RegisterTime')),
            ],
            options={
                'db_table': 'global_device_block',
            },
        ),
        migrations.CreateModel(
            name='GlobalLabelBlock',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('PrimaryLabel', models.TextField(db_column='LabelContent')),
                ('RegisterTime', models.DateTimeField(auto_now_add=True, db_column='RegisterTime')),
            ],
            options={
                'db_table': 'global_label_block',
            },
        ),
        migrations.CreateModel(
            name='GlobalWordIndex',
            fields=[
                ('id', models.AutoField(db_column='INDEX', primary_key=True, serialize=False)),
                ('Word', models.TextField(db_column='WORD', db_index=True)),
            ],
            options={
                'db_table': 'global_word_index',
            },
        ),
        migrations.CreateModel(
            name='LabelBlockId',
            fields=[
                ('BlockId', models.IntegerField(db_column='BLOCK_ID', db_index=True)),
                ('OutId', models.BigIntegerField(db_column='OUT_ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'global_node_id',
            },
        ),
    ]
