# Generated by Django 2.2 on 2019-07-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globaldeviceblock',
            name='DeviceId',
            field=models.SmallIntegerField(db_column='DeviceId', db_index=True),
        ),
        migrations.AlterField(
            model_name='globallabelblock',
            name='PrimaryLabel',
            field=models.TextField(db_column='LabelContent', db_index=True),
        ),
        migrations.AlterModelTable(
            name='deviceblockid',
            table='global_device_id',
        ),
    ]
