# Generated by Django 2.2 on 2019-07-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_auto_20190720_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalwordindex',
            name='Word',
            field=models.TextField(db_column='WORD', db_index=True, unique=True),
        ),
    ]
